### ISSUE TITLE
import .create_new_channelでエラー

### ISSUE THREAD

**Issue by matchasong** [matchasong/createSlackChannel#8]
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'src/main': invalid syntax (main.py, line 8)
Traceback (most recent call last):
  File "/var/task/src/main.py" Line 8
    import .create_new_channel

**Comment by matchasong** [comment]
import src.create_new_channel としたらエラー解消

**Comment by matchasong** [comment]
似たようなエラーが発生

```
[ERROR] NameError: name 'create_new_channel' is not defined
Traceback (most recent call last):
  File "/var/task/src/main.py", line 29, in handler
    raise e
  File "/var/task/src/main.py", line 21, in handler
    message_create = create_new_channel.create_new_channel(client)
```

**Comment by matchasong** [comment]
import src.create_new_channel as create_new_channel
としたらエラー解消
